name: flutter_login_hub
description: "A Flutter Package with login/signup functionalities to help speed up development."
version: 0.0.1
homepage: https://github.com/Pradipjadav05/flutter_login_hub.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
